filebeat.inputs:
  - type: filestream
    id: docker-container-logs
    prospector.scanner.symlinks: true
    parsers:
      - container:
          stream: stdout
          format: docker
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  
  - drop_event:
      when:
        regexp:
          container.name: ".*(filebeat|logstash).*"

  - decode_json_fields:
      fields: ["message"]
      target: "json"

output.logstash:
  hosts: ["logstash:5555"]
  protocol: tcp

logging.json: true
logging.metrics.enabled: false